// Summary letter to legal (Pieter Mulder CCMA matter): fleet / insurance control failures found in the fleet app review, on the ASI letterhead.
import fs from 'node:fs'; import JSZip from 'jszip';
const esc = (s) => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const run = (t, o = {}) => `<w:r><w:rPr>${o.bold ? '<w:b/>' : ''}${o.italic ? '<w:i/>' : ''}${o.size ? `<w:sz w:val="${o.size}"/><w:szCs w:val="${o.size}"/>` : ''}${o.color ? `<w:color w:val="${o.color}"/>` : ''}${o.hl ? '<w:highlight w:val="yellow"/>' : ''}</w:rPr><w:t xml:space="preserve">${esc(t)}</w:t></w:r>`;
const p = (parts, o = {}) => `<w:p><w:pPr><w:pStyle w:val="${o.style ?? 'Body'}"/>${o.align ? `<w:jc w:val="${o.align}"/>` : ''}${o.keep ? '<w:keepNext/>' : ''}<w:spacing w:before="${o.before ?? 0}" w:after="${o.after ?? 140}" w:line="259" w:lineRule="auto"/>${o.pageBreak ? '<w:pageBreakBefore/>' : ''}</w:pPr>${(Array.isArray(parts) ? parts : [parts]).map((x) => (typeof x === 'string' ? run(x, o) : run(x.t, { ...o, ...x }))).join('')}</w:p>`;
const num = (items) => items.map((t, i) => `<w:p><w:pPr><w:pStyle w:val="Body"/><w:ind w:left="567" w:hanging="425"/><w:spacing w:after="140" w:line="276" w:lineRule="auto"/></w:pPr>${run(`${i + 1}.`, { bold: true })}<w:r><w:tab/></w:r>${(Array.isArray(t) ? t : [t]).map((x) => (typeof x === 'string' ? run(x) : run(x.t, x))).join('')}</w:p>`).join('');
const cell = (t, w, o = {}) => `<w:tc><w:tcPr><w:tcW w:w="${w}" w:type="dxa"/>${o.shade ? `<w:shd w:val="clear" w:color="auto" w:fill="${o.shade}"/>` : ''}<w:tcMar><w:top w:w="45" w:type="dxa"/><w:bottom w:w="45" w:type="dxa"/><w:left w:w="90" w:type="dxa"/><w:right w:w="90" w:type="dxa"/></w:tcMar><w:vAlign w:val="top"/></w:tcPr><w:p><w:pPr><w:spacing w:before="0" w:after="0" w:line="259" w:lineRule="auto"/>${o.align ? `<w:jc w:val="${o.align}"/>` : ''}</w:pPr>${run(t, { size: 18, bold: o.bold, color: o.color })}</w:p></w:tc>`;
const table = (head, rows, widths, right = []) => `<w:tbl><w:tblPr><w:tblStyle w:val="TableGrid"/><w:tblW w:w="${widths.reduce((a, b) => a + b, 0)}" w:type="dxa"/><w:tblBorders><w:top w:val="single" w:sz="4" w:color="D9D6E3"/><w:left w:val="nil"/><w:bottom w:val="single" w:sz="4" w:color="D9D6E3"/><w:right w:val="nil"/><w:insideH w:val="single" w:sz="4" w:color="D9D6E3"/><w:insideV w:val="nil"/></w:tblBorders><w:tblLook w:val="04A0"/></w:tblPr><w:tblGrid>${widths.map((w) => `<w:gridCol w:w="${w}"/>`).join('')}</w:tblGrid><w:tr><w:trPr><w:tblHeader/><w:cantSplit/></w:trPr>${head.map((h, i) => cell(h, widths[i], { shade: '1B1B3A', color: 'FFFFFF', bold: true, align: right.includes(i) ? 'right' : undefined })).join('')}</w:tr>${rows.map((r, ri) => `<w:tr><w:trPr><w:cantSplit/></w:trPr>${r.map((c, i) => cell(c, widths[i], { align: right.includes(i) ? 'right' : undefined, shade: ri % 2 ? 'F5F4F8' : undefined })).join('')}</w:tr>`).join('')}</w:tbl>${p('', { after: 120 })}`;
const R = (n) => 'R ' + Math.round(n).toLocaleString('en-ZA').replace(/,/g, ' ');
const today = new Date().toLocaleDateString('en-ZA', { weekday: 'long', day: '2-digit', month: 'long', year: 'numeric' });
const PH = (t) => ({ t, hl: true });

const items = [
  ['1', 'Randburg solar system still insured after vacating the premises', 'Solar system at 344 Surrey Ave, Ferndale (policy COMM/806363, insured R1 238 483) remains on cover at R3 144.80 per month; premises vacated November 2024', '22 months × R3 144.80', R(69186)],
  ['2', 'Returned Avis vehicles left on the insurance policy', 'KZ95BVGP (returned Oct 2025), KY69NZGP (Jan 2026), KS04LMGP (Jul 2026) still insured on the September 2026 schedule; KR12ZNGP, KP92SRGP and KL79LLGP (all returned Mar 2026) were still insured in June 2026', 'R3 038 per month on the three still on cover; about R7 700 per month in June', R(20000)],
  ['3', 'WesBank maintenance contracts and fleet cards not cancelled', '8 disposed vehicles and 5 fleet cards of staff who had left still charged the R77.42 monthly contract fee in July and August 2026; KB33LPGP, KZ95BVGP and KY69NZGP billed for 12 to 14 months after return', 'R77.42 per item per month', R(3000)],
  ['4', 'Sold and returned vehicles never removed from the Avis fines-administration profile', '36 registrations that are not company vehicles were charged fine-administration fees on the August 2026 Avis statement (131 fees); returned vehicle KL79LLGP alone attracted 10 fees after hand-back; 48 of 94 vehicles have no nominated driver, so fines cannot be redirected', 'R57.50 per fine', R(7533)],
  ['5', 'Vehicle records not maintained', '8 Avis vehicles returned between July 2025 and July 2026 with no return recorded; dates had to be reconstructed from Avis credit notes. 14 owned vehicles with no fuel drawn for 14 months still carried as active, several still on insurance and maintenance contracts', 'Premiums and fees on idle vehicles', 'see 2, 3'],
];
const body = [
  p(today, { align: 'right' }),
  p('Benita da Silva', { bold: true, after: 0 }), p('ASI Group RCL', { after: 0 }), p('By e-mail', { after: 320 }),
  p([{ t: 'Re: CCMA matter — Pieter Louw Mulder (personnel no. 4077) — summary of fleet and insurance control failures', bold: true }], { after: 240 }),
  p('Dear Benita'),
  p(['In September 2026 we reconciled every fleet cost source for the first time in a fleet management application: the First Auto fuel-card statements, the WesBank managed-maintenance invoices, the Avis Fleet statements and vehicle report, the insurer\'s current policy schedule and the broker\'s premium breakdown, and our own vehicle and card-holder masters. The exercise showed that routine administration expected of the fleet and insurance function had not been performed for an extended period. The items below are drawn directly from supplier statements and the insurer\'s schedule and can each be evidenced by the underlying document.']),
  p(['Mr Mulder held the position of Procurement and Asset Manager, reporting to the Chief Financial Officer, from December 2024 until his dismissal following the disciplinary hearing of 12 August 2026. His signed job description (HMS/HR/JD/30, revision 01, signed by him on 18 November 2024) makes the following his personal responsibilities under "Roles and responsibilities – Assets": managing the service level agreements for vehicle registrations, licences and traffic offences; maintaining and updating the Company asset register; operating the vehicle tracking system and reviewing vehicle and fuel utilisation; managing and maintaining the insurance policies, including applications, claims and cancellations; reconciling the First Auto and WesBank statements monthly; managing fuel and maintenance expenses and investigating overspending; managing the entire lifecycle of assets including disposal; and conducting regular audits of the Company\'s assets nationwide. Every failure listed below falls within those duties and within his period of employment.']),
  p('Findings', { style: 'Header2', keep: true, before: 200, after: 120 }),
  table(['#', 'Failure', 'Evidence', 'Basis', 'Approx. cost'], items, [420, 2100, 4206, 1300, 1000], [4]),
  p([{ t: 'Total quantifiable cost to date: approximately ', bold: true }, { t: R(100000), bold: true }, ', excluding the insurance premiums and contract fees on the idle vehicles in item 5. The Randburg solar item alone accounts for roughly R69 000 and continues to accrue at R3 144.80 per month until cancelled.']),
  p('Pattern', { style: 'Header2', keep: true, before: 200, after: 120 }),
  num([
    'None of the eight Avis returns, the two vehicle sales or the five staff departures was passed on to the insurer, WesBank or Avis. Each supplier continued to bill until we found the charges in September 2026.',
    'The vehicle master used for insurance had not been reconciled to the Avis fleet or to fuel-card activity: 14 vehicles that had not moved for over a year were still carried as active, insured and on maintenance contract.',
    'Fines administration with Avis was left without nominated drivers on half the fleet and with 36 registrations that do not belong to the company, so fine fees accrued to the company with no accountability.',
    'The Randburg premises were vacated in November 2024, yet the solar installation there was never removed from the policy and has been paid for every month since.',
  ]),
  p('Supporting documents are available on request: Avis Fleet statements June to September 2026 and the September 2026 vehicle report; WesBank invoices CI00063310, CI00063311, CI00065190 and CI00065191; the OMART Insure policy schedule and September 2026 invoices; the broker\'s July 2026 premium breakdown; and the First Auto statements July 2025 to August 2026.', { size: 18 }),
  p('Please let me know what further detail or affidavit format you require.', { after: 360 }),
  p('Yours faithfully', { after: 720, keep: true }),
  p('Herman de Vries', { bold: true, after: 0, keep: true }), p('Chief Executive Officer', { after: 0, keep: true }), p('ASI Connect ICS', { after: 0 }),
].join('');

const tpl = 'C:/Users/User1/OneDrive - interconnect.co.za/Desktop/Claude/AutoSign/_config/letterhead_asi_connect.docx';
const z = await JSZip.loadAsync(fs.readFileSync(tpl)); let doc = await z.file('word/document.xml').async('string');
const sect = doc.match(/<w:sectPr[\s\S]*<\/w:sectPr>/)[0]; doc = doc.replace(/<w:body>[\s\S]*<\/w:body>/, `<w:body>${body}${sect}</w:body>`); z.file('word/document.xml', doc);
const out = 'C:/Users/User1/OneDrive - interconnect.co.za/Desktop/Claude/Fleet/Output/Letter to legal - fleet and insurance control failures (CCMA) v2.docx';
fs.writeFileSync(out, await z.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' })); console.log('wrote', out);
