import fs from 'node:fs'; import XLSX from 'xlsx'; XLSX.set_fs(fs); import { readFileSync } from 'node:fs'; import { createClient } from '@supabase/supabase-js'; import ExcelJS from 'exceljs';
for (const l of readFileSync('scripts/.env','utf8').split(/\r?\n/)) { const m = l.match(/^([A-Z_]+)\s*=\s*(.+)$/); if (m) process.env[m[1]] ??= m[2].trim(); }
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const norm = (s) => String(s ?? '').toUpperCase().replace(/[^A-Z0-9]/g, '');
const cartrackList = new Set(XLSX.utils.sheet_to_json(XLSX.read(fs.readFileSync('C:/Users/User1/Downloads/Interconnect Systems, CC VEHICLE LIST.xlsx'), { type: 'buffer' }).Sheets.Sheet1, { header: 1, defval: '' }).slice(4).map((r) => norm(r[0])).filter(Boolean));
const [{ data: veh }, { data: br }, { data: trk }] = await Promise.all([sb.from('fleet_vehicles').select('id,registration,year,make,model,branch_id,ownership,active,tracking_provider').eq('active', true).order('registration'), sb.from('fleet_branches').select('id,code,name'), sb.from('fleet_tracking_lines').select('reg,provider,total').eq('period', '2026-08')]);
const B = (id) => br.find((b) => b.id === id)?.name ?? ''; const ctInv = new Set(trk.filter((t) => t.provider === 'Cartrack').map((t) => norm(t.reg))); const trInv = new Set(trk.filter((t) => t.provider === 'Tracker').map((t) => norm(t.reg)));
const rows = veh.map((v) => { const r = norm(v.registration); const ct = cartrackList.has(r) || ctInv.has(r); const tr = trInv.has(r); const prov = ct && tr ? 'Both (check)' : ct ? 'Cartrack' : tr ? 'Tracker' : 'No tracker'; return { reg: v.registration, vehicle: `${v.year ?? ''} ${v.make ?? ''} ${v.model ?? ''}`.trim(), branch: B(v.branch_id), own: v.ownership === 'avis' ? 'Avis' : 'Owned', prov, list: cartrackList.has(r) ? 'yes' : '', ctInv: ctInv.has(r) ? 'yes' : '', trInv: trInv.has(r) ? 'yes' : '', master: v.tracking_provider ?? '' }; });
const counts = {}; for (const r of rows) counts[r.prov] = (counts[r.prov] ?? 0) + 1; console.log('active vehicles', rows.length, counts);
const byBranch = {}; for (const r of rows) { byBranch[r.branch] ??= { Cartrack: 0, Tracker: 0, 'No tracker': 0, 'Both (check)': 0 }; byBranch[r.branch][r.prov]++; }
const wb = new ExcelJS.Workbook(); const hdr = (ws, n) => { ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0E0B2E' } }; ws.views = [{ state: 'frozen', ySplit: 1 }]; ws.autoFilter = { from: { row: 1, column: 1 }, to: { row: n + 1, column: ws.columns.length } }; };
const s = wb.addWorksheet('Summary'); s.columns = [{ header: 'Branch', key: 'b', width: 24 }, { header: 'Cartrack', key: 'c', width: 10 }, { header: 'Tracker', key: 't', width: 10 }, { header: 'No tracker', key: 'n', width: 11 }, { header: 'Both (check)', key: 'x', width: 12 }, { header: 'Total', key: 'tot', width: 8 }];
for (const [b, c] of Object.entries(byBranch).sort()) s.addRow({ b, c: c.Cartrack, t: c.Tracker, n: c['No tracker'], x: c['Both (check)'], tot: c.Cartrack + c.Tracker + c['No tracker'] + c['Both (check)'] });
const tot = s.addRow({ b: 'Total', c: counts.Cartrack ?? 0, t: counts.Tracker ?? 0, n: counts['No tracker'] ?? 0, x: counts['Both (check)'] ?? 0, tot: rows.length }); tot.font = { bold: true }; hdr(s, Object.keys(byBranch).length + 1);
s.addRow([]); s.addRow(['Source: Cartrack vehicle list (Interconnect Systems CC) and Cartrack August 2026 invoice = Cartrack; Tracker August 2026 invoice = Tracker; neither = no tracker. Active vehicles on the fleet master only.']);
for (const [name, filt] of [['Cartrack', 'Cartrack'], ['Tracker', 'Tracker'], ['No tracker', 'No tracker'], ['Both (check)', 'Both (check)']]) { const ws = wb.addWorksheet(name); ws.columns = [{ header: 'Reg', key: 'reg', width: 12 }, { header: 'Vehicle', key: 'vehicle', width: 34 }, { header: 'Branch', key: 'branch', width: 22 }, { header: 'Owned / Avis', key: 'own', width: 12 }, { header: 'On Cartrack list', key: 'list', width: 14 }, { header: 'Cartrack Aug invoice', key: 'ctInv', width: 18 }, { header: 'Tracker Aug invoice', key: 'trInv', width: 18 }, { header: 'Master field', key: 'master', width: 12 }]; const rs = rows.filter((r) => r.prov === filt).sort((a, b) => a.branch.localeCompare(b.branch) || a.reg.localeCompare(b.reg)); for (const r of rs) ws.addRow(r); hdr(ws, rs.length); }
const out = 'C:/Users/User1/OneDrive - interconnect.co.za/Desktop/Claude/Fleet/Output/Active vehicles by tracking provider.xlsx'; await wb.xlsx.writeFile(out); console.log('wrote', out);
console.log('No tracker:', rows.filter((r) => r.prov === 'No tracker').map((r) => `${r.reg} (${r.branch}, ${r.own})`).join('; '));
console.log('Both:', rows.filter((r) => r.prov === 'Both (check)').map((r) => r.reg).join(', ') || 'none');
