// Traveller list for Herman to complete: e-mail, manager (who approves), Fleet access. Reads back with scripts/apply-travellers.mjs.
import { readFileSync } from 'node:fs'; import { createClient } from '@supabase/supabase-js'; import ExcelJS from 'exceljs';
for (const l of readFileSync('scripts/.env','utf8').split(/\r?\n/)) { const m = l.match(/^([A-Z_]+)\s*=\s*(.+)$/); if (m) process.env[m[1]] ??= m[2].trim(); }
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const [{ data: emps }, { data: br }, { data: logs }, { data: users }] = await Promise.all([sb.from('fleet_employees').select('*').eq('active', true).order('emp_no'), sb.from('fleet_branches').select('id,code,name'), sb.from('fleet_travel_logs').select('employee_id,period'), sb.auth.admin.listUsers({ perPage: 1000 })]);
const B = (id) => br.find((b) => b.id === id)?.name ?? ''; const hasLogin = new Set(users.users.map((u) => (u.email ?? '').toLowerCase()));
const trav = emps.filter((e) => e.fuel_rate || e.maint_rate || logs.some((l) => l.employee_id === e.id));
const wb = new ExcelJS.Workbook(); const ws = wb.addWorksheet('Travellers');
ws.columns = [{ header: 'Emp No', key: 'emp_no', width: 8 }, { header: 'Name', key: 'name', width: 30 }, { header: 'Branch', key: 'branch', width: 20 }, { header: 'Category', key: 'cat', width: 12 }, { header: 'E-mail (current, guessed)', key: 'email_now', width: 36 }, { header: 'E-mail (correct)', key: 'email', width: 36 }, { header: 'Manager (who approves the log)', key: 'manager', width: 30 }, { header: "Manager's e-mail", key: 'manager_email', width: 36 }, { header: 'Fleet access (driver / manager / none)', key: 'access', width: 20 }, { header: 'Has a login already', key: 'login', width: 12 }, { header: 'Fuel R/km', key: 'fuel', width: 10 }, { header: 'Maint R/km', key: 'maint', width: 10 }, { header: 'Own vehicle', key: 'reg', width: 12 }, { header: 'Logs on file', key: 'logs', width: 12 }, { header: 'ID (do not change)', key: 'id', width: 8 }];
for (const e of trav) ws.addRow({ emp_no: e.emp_no, name: e.full_name, branch: B(e.branch_id), cat: e.category === 'Exec' ? 'Directors' : e.category, email_now: e.email ?? '', email: e.notes?.includes('auto-generated') ? '' : (e.email ?? ''), manager: '', manager_email: '', access: 'driver', login: hasLogin.has((e.email ?? '').toLowerCase()) ? 'yes' : '', fuel: e.fuel_rate, maint: e.maint_rate, reg: e.vehicle_reg ?? '', logs: [...new Set(logs.filter((l) => l.employee_id === e.id).map((l) => l.period))].sort().join(', '), id: e.id });
ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } }; ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF0E0B2E' } }; ws.views = [{ state: 'frozen', xSplit: 2, ySplit: 1 }]; ws.autoFilter = { from: 'A1', to: `O${trav.length + 1}` };
for (const key of ['email', 'manager', 'manager_email', 'access']) ws.getColumn(key).eachCell((c, r) => { if (r > 1) c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF9C4' } } });
ws.getColumn('email_now').eachCell((c, r) => { if (r > 1) c.font = { color: { argb: 'FF94A3B8' } } });
const notes = wb.addWorksheet('How to complete'); notes.getColumn(1).width = 110;
[['Yellow columns are the ones to complete.'], ['E-mail (correct): the address the person signs in with and receives mail on. Most current addresses were generated as firstname.surname@asiconnect.co.za and have not been verified.'], ['Manager: type the manager\'s name as it appears in the Name column if the manager is also a traveller, otherwise give the manager\'s e-mail in the next column. The manager receives the approval e-mail.'], ['Fleet access: driver = captures own travel logs; manager = also approves logs of the people who name them as manager; none = no login (log captured on their behalf).'], ['Has a login already: this e-mail already signs in to ASI Budget or ASI Excellence — the same password will work for Fleet.'], ['Do not change the ID column; it links the row back to the record.'], ['Save the file and drop it back in the Fleet folder; I will load the e-mails, managers and access in one go.']].forEach((r) => notes.addRow(r));
const out = 'C:/Users/User1/OneDrive - interconnect.co.za/Desktop/Claude/Fleet/Output/Travellers - e-mail and manager list.xlsx'; await wb.xlsx.writeFile(out); console.log(`wrote ${out}: ${trav.length} travellers, ${trav.filter((e) => hasLogin.has((e.email ?? '').toLowerCase())).length} with an existing login, ${trav.filter((e) => e.notes?.includes('auto-generated')).length} e-mails guessed`);
