import fs from 'node:fs'; import XLSX from 'xlsx'; XLSX.set_fs(fs); import { readFileSync } from 'node:fs'; import { createClient } from '@supabase/supabase-js';
for (const l of readFileSync('scripts/.env','utf8').split(/\r?\n/)) { const m = l.match(/^([A-Z_]+)\s*=\s*(.+)$/); if (m) process.env[m[1]] ??= m[2].trim(); }
const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, { auth: { persistSession: false } });
const REG = process.argv[2] ?? 'LF36TRGP'; const norm = (s) => String(s ?? '').toUpperCase().replace(/[^A-Z0-9]/g, '');
const [{ data: v }, { data: br }] = await Promise.all([sb.from('fleet_vehicles').select('*').eq('registration', REG).single(), sb.from('fleet_branches').select('id,code,name')]);
const B = (id) => br.find((b) => b.id === id)?.name ?? '';
console.log('MASTER:', { reg: v.registration, make: v.make, model: v.model, year: v.year, branch: B(v.branch_id), category: v.category, ownership: v.ownership, mva: v.avis_mva, insured: v.insured_value, tracking: v.tracking_provider, active: v.active, lease_end: v.lease_end });
const { data: al } = await sb.from('fleet_allocations').select('branch_id,category,effective_from,note').eq('vehicle_id', v.id); console.log('allocations:', al.map((a) => `${a.effective_from} ${B(a.branch_id)} ${a.category}`).join('; '));
const { data: cards } = await sb.from('fleet_cards').select('id,fa_driver_name,holder_type,active,notes').eq('fa_reg', REG); console.log('cards:', cards);
// Avis history
const { data: avis } = await sb.from('fleet_avis_lines').select('period,transaction_type,transaction_date,rental_excl,amount_due,document_no,cost_centre_name,kilometers').eq('reg', REG).order('period'); const g = {}; for (const l of avis) { g[l.period] = g[l.period] ?? { due: 0, types: [] }; g[l.period].due += Number(l.amount_due); g[l.period].types.push(`${l.transaction_type}${l.transaction_type !== 'MINV' ? ' R' + l.amount_due : ''}`); }
console.log('\nAVIS by statement month:'); for (const [p, x] of Object.entries(g)) console.log(`  ${p}  due R ${x.due.toFixed(2).padStart(10)}  ${x.types.join(', ')}`);
// Avis active report
const rep = XLSX.utils.sheet_to_json(XLSX.read(fs.readFileSync('C:/Users/User1/Downloads/Customer Monthly Report ASI CONNECT SEPT 2026.xlsx'), { type: 'buffer', cellDates: true }).Sheets.REPORT, { defval: '' }).find((r) => norm(r['REGISTRATION NUMBER']) === REG);
if (rep) { const d = (x) => (x instanceof Date ? x.toISOString().slice(0, 10) : x); console.log('\nAVIS CONTRACT (Sept report):'); for (const k of ['COST CENTRE NAME', 'MRM DESCRIPTION', 'DRIVER NAME', 'RENTAL AMOUNT', 'MAINT CHARGE OUT TOTAL', 'INSTALLATION DATE', 'CONTRACT END DATE', 'LAST CONTRACT MONTHS', 'MONTHS LEFT', 'LAST CONTRACT KM', 'LAST ODOMETER READING', 'LAST ODOMETER DATE', 'ACTUAL AVERAGE KM PER MONTH', 'AVERAGE CONTRACT KM PER MONTH', 'PROJECTED KMS AT CONTRACT END', 'EXCESS KM RATE', 'EXCESS KILOMETRE CHARGE', 'LAST SERVICE DATE', 'LAST SERVICE KM', 'SERVICE INTERVAL KM', 'TAKE ON KILOMETRES', 'TOTAL AVIS COST', 'COMMENTS', 'FUEL TYPE', 'C/KM ACTUAL']) console.log(`  ${k.padEnd(30)} ${d(rep[k])}`); }
// fuel card: YTD workbook blocks + app lines
const rows = XLSX.utils.sheet_to_json(XLSX.read(fs.readFileSync('C:/Users/User1/Downloads/YTD Running Cost Fleet 2025 - 2026.xls'), { type: 'buffer' }).Sheets['First Auto Info'], { header: 1, defval: '' });
const hdr = rows[2].map(String); const iReg = hdr.findIndex((c) => /reg num/i.test(c)), iFuel = hdr.findIndex((c) => /fuel mth/i.test(c)), iOdo = hdr.findIndex((c) => /odo close/i.test(c)), iPrev = hdr.findIndex((c) => /odo prev/i.test(c)), iKm = hdr.findIndex((c) => /^kms$/i.test(c.trim())), iLit = hdr.findIndex((c) => /litre total/i.test(c)), iToll = hdr.findIndex((c) => /toll excl/i.test(c)), iDrv = hdr.findIndex((c) => /driver/i.test(c));
const months = ['2025-07','2025-08','2025-09','2025-10','2025-11','2025-12','2026-01','2026-02','2026-03','2026-04','2026-05','2026-06']; let i = 0; const fuel = [];
for (const r of rows.slice(3)) if (norm(r[iReg]) === REG) fuel.push({ period: months[i++], driver: r[iDrv], fuel: Number(r[iFuel]) || 0, litres: Number(r[iLit]) || 0, km: Number(r[iKm]) || 0, prev: r[iPrev], odo: r[iOdo], toll: Number(r[iToll]) || 0 });
const { data: fa } = await sb.from('fleet_fa_lines').select('period,fa_driver_name,fuel,litres,kms,odo_prev,odo_close,toll_excl').eq('fa_reg', REG).order('period'); for (const l of fa) fuel.push({ period: l.period, driver: l.fa_driver_name, fuel: Number(l.fuel), litres: Number(l.litres) || 0, km: Number(l.kms) || 0, prev: l.odo_prev, odo: l.odo_close, toll: Number(l.toll_excl) });
console.log('\nFUEL CARD by month:'); for (const x of fuel) console.log(`  ${x.period}  ${String(x.driver).padEnd(12)} fuel R ${x.fuel.toFixed(0).padStart(6)}  ${x.litres.toFixed(0).padStart(4)} L  ${String(x.km).padStart(5)} km  odo ${x.prev}→${x.odo}  ${x.km && x.litres ? (100 * x.litres / x.km).toFixed(1) + ' L/100km' : ''}  toll ${x.toll.toFixed(0)}`);
const tf = fuel.reduce((s, x) => s + x.fuel, 0), tk = fuel.reduce((s, x) => s + x.km, 0), tl = fuel.reduce((s, x) => s + x.litres, 0); console.log(`  14 months: fuel R ${tf.toFixed(0)}, ${tk} km, ${tl.toFixed(0)} L → ${tk ? (tf / tk).toFixed(2) : '-'} R/km fuel, ${tk && tl ? (100 * tl / tk).toFixed(1) : '-'} L/100km`);
for (const [t, sel, col] of [['fleet_maint_lines', 'period,billing_type,supplier,item_desc,total,order_date', 'reg'], ['fleet_tracking_lines', 'period,provider,total', 'reg'], ['fleet_insurance_lines', 'period,premium,vat,retail_value', 'reg']]) { const { data } = await sb.from(t).select(sel).eq(col, REG).order('period'); console.log(`\n${t}:`, data.length ? data.map((x) => Object.values(x).join(' | ')).join('\n  ') : 'none'); }
const { data: fines } = await sb.from('fleet_avis_lines').select('period,transaction_date').eq('reg', REG).eq('transaction_type', 'FINESINV'); console.log('\nfines:', fines.length, fines.map((f) => f.transaction_date).join(', '));
const { data: logs } = await sb.from('fleet_travel_logs').select('period,status,business_km,private_km,fleet_employees(full_name)').eq('vehicle_reg', REG); console.log('travel logs:', logs);
